name: chemrep
channels:
  - rdkit
  - conda-forge

dependencies:
  - python=3
  - keras=2.0.6
  - h5py=2.10.0
  - tensorflow
  - hdf5
  - pandas
  - scikit-learn
  - boost
  - rdkit
  - yaml
  - numpy
  - matplotlib
  - cairosvg
